/* Currículo progressivo de fundamentos. Conteúdo original, sem dependências externas. */
(function () {
  "use strict";

  const units = [
    { id: "logica", order: 0, title: "Lógica e algoritmos", short: "Lógica", description: "Pensar em sequência, estado, decisões e repetição antes da sintaxe.", concepts: ["entrada → processamento → saída", "estado das variáveis", "expressões verdadeiras e falsas", "decomposição e casos-limite"], prerequisites: [] },
    { id: "sintaxe", order: 1, title: "Sintaxe essencial", short: "Sintaxe", description: "Escrever instruções que o interpretador consegue compreender.", concepts: ["identificadores e palavras-chave", "dois-pontos e indentação", "comentários", "atribuição não é comparação"], prerequisites: ["logica"] },
    { id: "variaveis", order: 2, title: "Variáveis e tipos", short: "Variáveis", description: "Entender nomes, valores, atribuição, referências e tipagem dinâmica.", concepts: ["atribuição e reatribuição", "int, float, str e bool", "type()", "nomes e referências"], prerequisites: ["sintaxe"] },
    { id: "numeros", order: 3, title: "Números e operadores", short: "Números", description: "Calcular com segurança e prever a ordem das operações.", concepts: ["int e float", "/, //, % e **", "conversões", "precedência e parênteses"], prerequisites: ["variaveis"] },
    { id: "strings", order: 4, title: "Strings", short: "Strings", description: "Tratar texto como sequência: acessar, recortar, buscar e formatar.", concepts: ["aspas e escapes", "índices e slicing", "métodos de texto", "concatenação e f-strings"], prerequisites: ["variaveis"] },
    { id: "entrada", order: 5, title: "Entrada e saída", short: "Entrada/saída", description: "Transformar dados lidos em valores úteis e apresentar resultados exatos.", concepts: ["print()", "input() sempre retorna str", "int() e float()", "entrada, processamento e saída"], prerequisites: ["numeros", "strings"] },
    { id: "condicoes", order: 6, title: "Condições", short: "Condições", description: "Escolher caminhos com comparações e lógica booleana.", concepts: ["if, elif e else", "comparações", "and, or e not", "ordem das condições"], prerequisites: ["entrada"] },
    { id: "lacos", order: 7, title: "Laços", short: "Laços", description: "Repetir com controle, acumuladores e condições de parada.", concepts: ["for e range()", "while", "contadores e acumuladores", "laços aninhados"], prerequisites: ["condicoes"] },
    { id: "listas", order: 8, title: "Listas", short: "Listas", description: "Organizar coleções e percorrê-las sem perder casos extremos.", concepts: ["índices e slicing", "append()", "percorrer e filtrar", "mutação e lista vazia"], prerequisites: ["lacos"] },
    { id: "funcoes", order: 9, title: "Funções", short: "Funções", description: "Encapsular soluções com parâmetros, retorno e escopo.", concepts: ["def e chamada", "parâmetros", "return x print", "escopo e composição"], prerequisites: ["listas"] },
    { id: "depuracao", order: 10, title: "Depuração e integração", short: "Depuração", description: "Ler erros, testar hipóteses e combinar os fundamentos.", concepts: ["erros de sintaxe e execução", "casos de teste", "laços infinitos", "corrigir antes de reescrever"], prerequisites: ["funcoes"] }
  ];

  const unitById = Object.fromEntries(units.map(unit => [unit.id, unit]));
  const group = unitId => String(unitById[unitId].order).padStart(2, "0") + " · " + unitById[unitId].title;
  const defaults = (unit, skills) => ({ unit, group: group(unit), skills });

  function choice(id, unit, title, prompt, options, correct, hint, note, skills) {
    return {
      id, ...defaults(unit, skills), title, kind: "choice", prompt,
      rule: "Escolha uma alternativa antes de verificar.",
      options: options.map((label, index) => ({ value: String(index), label })), answer: String(correct),
      starter: "", hint, solution: options[correct], note
    };
  }

  function order(id, unit, title, prompt, lines, hint, note, skills) {
    return {
      id, ...defaults(unit, skills), title, kind: "order", prompt,
      rule: "Use as setas para colocar todas as etapas na ordem correta.", lines,
      answer: lines.join("\n"), starter: "", hint, solution: lines.join("\n"), note
    };
  }

  function trace(id, unit, title, prompt, code, answer, hint, note, skills) {
    return {
      id, ...defaults(unit, skills), title, kind: "trace", prompt,
      rule: "Não execute. Acompanhe os valores e escreva a saída, uma linha por vez.", code, answer,
      starter: "", hint, solution: answer, note
    };
  }

  function program(id, unit, title, prompt, rule, cases, starter, hint, solution, note, skills, extra = {}) {
    return { id, ...defaults(unit, skills), title, kind: "program", prompt, rule, cases, starter, hint, solution, note, ...extra };
  }

  function fn(id, unit, title, name, prompt, rule, cases, starter, hint, solution, note, skills, extra = {}) {
    return { id, ...defaults(unit, skills), title, kind: "function", fn: name, prompt, rule, cases, starter, hint, solution, note, ...extra };
  }

  const additions = [
    // 00 · Lógica e algoritmos (9)
    order("logica-sequencia", "logica", "Uma receita em ordem", "Organize o algoritmo que soma dois números.", ["Ler o primeiro número", "Ler o segundo número", "Somar os dois valores", "Mostrar o resultado"], "Primeiro obtenha os dados; só depois calcule e apresente.", "Um algoritmo é uma sequência finita e ordenada de passos.", ["logica"]),
    choice("logica-processamento", "logica", "Entrada, processamento ou saída?", "No problema “ler duas notas e mostrar a média”, qual etapa é o processamento?", ["Ler as duas notas", "Somar as notas e dividir por 2", "Mostrar a média", "Digitar o programa"], 1, "Processamento é a transformação aplicada aos dados de entrada.", "Ler é entrada; calcular é processamento; mostrar é saída.", ["logica"]),
    choice("logica-estado", "logica", "Estado de uma variável", "Começando com x = 4, depois x = x + 3 e x = x * 2, qual é o valor final?", ["10", "11", "14", "18"], 2, "Atualize o valor uma instrução de cada vez.", "A variável guarda 4, depois 7 e finalmente 14.", ["logica", "variaveis"]),
    choice("logica-verdade", "logica", "Verdadeiro ou falso", "Qual expressão é verdadeira para idade = 17?", ["idade >= 18", "idade < 10", "idade == 17", "idade != 17"], 2, "Substitua idade por 17 em cada comparação.", "Uma comparação produz um valor booleano: True ou False.", ["logica", "condicoes"]),
    choice("logica-caminho", "logica", "Escolher um caminho", "Se a regra é “desconto para idade menor que 12”, quem recebe desconto?", ["Uma pessoa de 12 anos", "Uma pessoa de 15 anos", "Uma pessoa de 11 anos", "Todas as pessoas"], 2, "“Menor que” não inclui o limite.", "Traduzir exatamente as palavras evita erros de fronteira.", ["logica", "condicoes"]),
    trace("logica-contador", "logica", "Acompanhar um contador", "Preveja a saída do pequeno algoritmo.", "contador = 0\ncontador = contador + 1\ncontador = contador + 1\nprint(contador)", "2", "Anote o valor depois de cada atribuição.", "Um contador normalmente começa em zero e aumenta uma unidade por evento.", ["logica", "acumuladores"]),
    choice("logica-parada", "logica", "Quando a repetição termina?", "Um contador começa em 1 e aumenta enquanto contador <= 5. Qual valor faz a condição ficar falsa pela primeira vez?", ["4", "5", "6", "Nunca termina"], 2, "Depois de usar 5, o contador aumenta novamente.", "A condição de parada deve se tornar falsa em algum momento.", ["logica", "lacos"]),
    choice("logica-limites", "logica", "Casos que revelam defeitos", "Para testar uma função que divide a soma de uma lista pelo tamanho, qual caso é indispensável?", ["Uma lista ordenada", "Uma lista vazia", "Uma lista com dez números", "Uma lista chamada valores"], 1, "Procure a operação que pode ficar impossível.", "Lista vazia produz tamanho zero e expõe uma divisão por zero.", ["logica", "depuracao"]),
    order("logica-media", "logica", "Decompor antes de programar", "Organize a solução para calcular a média de três valores.", ["Identificar as três entradas", "Somar os três valores", "Dividir a soma por 3", "Apresentar a média"], "Separe obtenção dos dados, transformação e apresentação.", "Decompor reduz a carga mental quando chegar a hora da sintaxe.", ["logica"]),

    // 01 · Sintaxe essencial (8 novos + ola)
    choice("sintaxe-identificador", "sintaxe", "Um nome válido", "Qual nome pode ser usado como variável em Python?", ["2notas", "nota-final", "nota_final", "class"], 2, "Um identificador não começa com número, não contém hífen e não pode ser palavra-chave.", "Underscore é permitido em identificadores.", ["sintaxe", "variaveis"]),
    choice("sintaxe-keyword", "sintaxe", "Palavra reservada", "Qual opção não pode ser nome de variável porque é palavra-chave?", ["resultado", "media", "while", "aluno"], 2, "É uma palavra usada para construir um laço.", "Palavras-chave fazem parte da gramática da linguagem.", ["sintaxe"]),
    choice("sintaxe-igual", "sintaxe", "Atribuir ou comparar", "Qual linha pergunta se x possui o valor 10?", ["x = 10", "x == 10", "x := 10", "10 = x"], 1, "Um sinal guarda; dois sinais comparam.", "x = 10 altera o estado; x == 10 produz True ou False.", ["sintaxe", "condicoes"]),
    choice("sintaxe-indentacao", "sintaxe", "Bloco bem indentado", "Qual trecho possui uma condição válida?", ["if x > 0:\nprint(x)", "if x > 0\n    print(x)", "if x > 0:\n    print(x)", "if (x > 0) then:\n    print(x)"], 2, "Procure dois-pontos e quatro espaços no corpo.", "Python usa indentação para delimitar blocos.", ["sintaxe"]),
    choice("sintaxe-dois-pontos", "sintaxe", "Onde entram os dois-pontos?", "Qual instrução abre corretamente um laço?", ["for n in range(3)", "for n in range(3):", "for: n in range(3)", "for n: range(3)"], 1, "Os dois-pontos aparecem no final do cabeçalho.", "if, elif, else, for, while e def abrem blocos com dois-pontos.", ["sintaxe", "lacos"]),
    trace("sintaxe-comentario", "sintaxe", "Comentário não executa", "Preveja a única linha mostrada.", "# print(10)\nprint(20) # print(30)", "20", "Tudo depois de # na mesma linha é comentário.", "Comentários são ignorados pelo interpretador.", ["sintaxe", "rastreamento"]),
    order("sintaxe-bloco", "sintaxe", "Montar uma condição", "Organize um programa que imprime positivo quando x é maior que zero.", ["x = 5", "if x > 0:", "    print(\"positivo\")"], "A variável precisa existir antes da comparação; o print pertence ao bloco.", "A indentação comunica a estrutura do programa.", ["sintaxe", "condicoes"]),
    program("sintaxe-corrigir", "sintaxe", "Consertar a primeira frase", "Corrija o código para mostrar exatamente: Python funciona!", "Use uma única chamada de print().", [{ inputs: [], expected: "Python funciona!" }], "# print(Python funciona!)\n", "O texto precisa estar entre aspas e a chamada precisa de parênteses.", "print(\"Python funciona!\")", "Aspas delimitam a string; parênteses fazem parte da chamada.", ["sintaxe"]),

    // 02 · Variáveis e tipos (9)
    trace("var-atribuicao", "variaveis", "Guardar e recuperar", "Qual valor é mostrado?", "idade = 20\nprint(idade)", "20", "O nome idade passa a referenciar o valor 20.", "A atribuição não mostra nada sozinha.", ["variaveis", "rastreamento"]),
    trace("var-reatribuicao", "variaveis", "O valor mais recente", "Acompanhe as reatribuições.", "pontos = 10\npontos = 15\npontos = pontos + 2\nprint(pontos)", "17", "Uma nova atribuição substitui a referência anterior.", "A execução ocorre de cima para baixo.", ["variaveis", "rastreamento"]),
    trace("var-multipla", "variaveis", "Atribuição múltipla", "Preveja as duas linhas.", "a, b = 3, 8\nprint(a)\nprint(b)", "3\n8", "Os valores são associados na mesma ordem dos nomes.", "Atribuição múltipla pode inicializar vários nomes de uma vez.", ["variaveis", "rastreamento"]),
    choice("var-tipo", "variaveis", "Descobrir o tipo", "Qual é o resultado de type(3.0)?", ["int", "float", "str", "bool"], 1, "A presença do ponto decimal importa.", "3 e 3.0 têm valores próximos, mas tipos diferentes.", ["variaveis", "tipos"]),
    trace("var-dinamica", "variaveis", "Tipagem dinâmica", "Qual tipo é mostrado no final?", "valor = 10\nvalor = \"dez\"\nprint(type(valor).__name__)", "str", "Considere somente a atribuição mais recente.", "O nome pode passar a referenciar um objeto de outro tipo.", ["variaveis", "tipos"]),
    trace("var-referencia", "variaveis", "Duas referências", "Listas são mutáveis. Preveja a saída.", "a = [1, 2]\nb = a\nb.append(3)\nprint(a)", "[1, 2, 3]", "a e b apontam para a mesma lista.", "Alterar o objeto por uma referência também é visível pela outra.", ["variaveis", "listas", "rastreamento"]),
    choice("var-del", "variaveis", "Depois de del", "O que acontece ao executar x = 5, depois del x e finalmente print(x)?", ["Mostra 5", "Mostra None", "Ocorre NameError", "Ocorre SyntaxError"], 2, "del remove o nome do ambiente atual.", "Usar um nome inexistente produz NameError.", ["variaveis", "depuracao"]),
    choice("var-case", "variaveis", "Maiúsculas fazem diferença", "Depois de idade = 20, o que acontece com print(Idade)?", ["Mostra 20", "Mostra idade", "Ocorre NameError", "Mostra None"], 2, "idade e Idade são identificadores diferentes.", "Nomes em Python são case-sensitive.", ["variaveis", "depuracao"]),
    program("var-troca", "variaveis", "Trocar dois valores", "Defina a = 4 e b = 9, troque os valores e mostre a e b separados por espaço.", "A saída deve ser 9 4. Você pode usar atribuição múltipla.", [{ inputs: [], expected: "9 4" }], "a = 4\nb = 9\n", "Em Python, a, b = b, a faz a troca diretamente.", "a = 4\nb = 9\na, b = b, a\nprint(a, b)", "A expressão à direita é avaliada antes das novas atribuições.", ["variaveis", "sintaxe"]),

    // 03 · Números e operadores (7 novos + media/divisao)
    choice("num-tipos", "numeros", "Inteiro ou decimal", "Qual literal cria um float?", ["8", "-3", "8.0", "0b1000"], 2, "Procure o ponto decimal.", "Um literal com ponto é float, mesmo quando a parte decimal é zero.", ["tipos", "numeros"]),
    choice("num-divisao", "numeros", "A barra sempre divide", "Qual é o valor de 7 / 2 em Python 3?", ["3", "3.0", "3.5", "4"], 2, "/ produz divisão real.", "Use // quando precisar do quociente inteiro por piso.", ["numeros"]),
    trace("num-floor-mod", "numeros", "Quociente e resto", "Preveja as duas linhas.", "print(17 // 5)\nprint(17 % 5)", "3\n2", "17 contém três grupos completos de 5 e sobra 2.", "// e % descrevem a mesma divisão por perspectivas diferentes.", ["numeros", "rastreamento"]),
    trace("num-precedencia", "numeros", "Quem calcula primeiro?", "Preveja o resultado sem executar.", "resultado = 3 + 4 * 5\nprint(resultado)", "23", "Multiplicação tem precedência maior que adição.", "Parênteses podem alterar a ordem padrão.", ["numeros", "rastreamento"]),
    trace("num-conversao", "numeros", "Converter muda o resultado", "Preveja a saída.", "texto = \"12\"\nnumero = int(texto)\nprint(numero + 3)", "15", "int() cria um inteiro a partir do texto numérico.", "Sem conversão, texto e inteiro não podem ser somados.", ["numeros", "tipos", "rastreamento"]),
    choice("num-cientifica", "numeros", "Notação científica", "Qual é o valor de 3e2?", ["3.2", "30", "300.0", "3000"], 2, "e2 significa multiplicar por 10².", "Notação científica com e produz float.", ["numeros", "tipos"]),
    program("num-temperatura", "numeros", "Celsius para Fahrenheit", "Leia uma temperatura Celsius e mostre Fahrenheit usando F = C * 9 / 5 + 32.", "Use float() e imprima somente o número.", [{ inputs: ["0"], expected: "32.0" }, { inputs: ["100"], expected: "212.0" }, { inputs: ["-40"], expected: "-40.0" }], "celsius = float(input())\n", "Respeite a ordem: multiplique, divida e depois some 32.", "celsius = float(input())\nfahrenheit = celsius * 9 / 5 + 32\nprint(fahrenheit)", "-40 é um caso interessante porque as duas escalas coincidem.", ["numeros", "entrada"] , { numericOutput: true }),

    // 04 · Strings (9 novos + vogais)
    choice("str-aspas", "strings", "Aspas dentro do texto", "Qual linha mostra: Ela disse \"oi\"?", ["print(\"Ela disse \"oi\"\")", "print('Ela disse \"oi\"')", "print(Ela disse oi)", "print['Ela disse oi']"], 1, "Use aspas simples por fora quando há aspas duplas dentro.", "Também seria possível escapar as aspas internas com barra invertida.", ["strings", "sintaxe"]),
    trace("str-indices", "strings", "Primeiro e último caractere", "Preveja a saída.", "texto = \"Python\"\nprint(texto[0])\nprint(texto[-1])", "P\nn", "Índice zero é o primeiro; -1 é o último.", "Índices negativos contam a partir do final.", ["strings", "rastreamento"]),
    trace("str-slicing", "strings", "Recortar uma string", "O limite final do slicing fica de fora.", "palavra = \"algoritmo\"\nprint(palavra[0:4])", "algo", "Use os índices 0, 1, 2 e 3.", "Slicing segue a ideia de início incluso e fim exclusivo.", ["strings", "rastreamento"]),
    fn("str-inverter", "strings", "Texto ao contrário", "inverte", "Escreva inverte(texto), que retorna o texto invertido.", "Use slicing com passo -1.", [{ args: ["python"], expected: "nohtyp" }, { args: ["a"], expected: "a" }, { args: [""], expected: "" }], "def inverte(texto):\n    pass\n", "texto[::-1] percorre do fim para o começo.", "def inverte(texto):\n    return texto[::-1]", "String vazia também deve funcionar.", ["strings", "funcoes"]),
    fn("str-normalizar", "strings", "Limpar e colocar em minúsculas", "normaliza", "Escreva normaliza(texto), que remove espaços das pontas e retorna tudo em minúsculas.", "Use strip() e lower().", [{ args: ["  Python  "], expected: "python" }, { args: ["CASA"], expected: "casa" }, { args: ["  Um Dia"], expected: "um dia" }], "def normaliza(texto):\n    pass\n", "Métodos podem ser encadeados.", "def normaliza(texto):\n    return texto.strip().lower()", "Cada método devolve uma nova string.", ["strings", "funcoes"]),
    fn("str-substituir", "strings", "Trocar separadores", "troca_hifens", "Escreva troca_hifens(texto), que substitui todos os hífens por espaços.", "Use replace().", [{ args: ["python-de-cabeca"], expected: "python de cabeca" }, { args: ["semhifen"], expected: "semhifen" }, { args: ["a-b-c"], expected: "a b c" }], "def troca_hifens(texto):\n    pass\n", "replace(antigo, novo) devolve outra string.", "def troca_hifens(texto):\n    return texto.replace(\"-\", \" \")", "O texto original não é alterado.", ["strings", "funcoes"]),
    fn("str-iniciais", "strings", "Iniciais de um nome", "iniciais", "Escreva iniciais(nome), que separa por espaços e retorna as primeiras letras juntas em maiúsculas.", "Exemplo: 'Ada Lovelace' retorna 'AL'.", [{ args: ["Ada Lovelace"], expected: "AL" }, { args: ["alan mathison turing"], expected: "AMT" }, { args: ["Python"], expected: "P" }], "def iniciais(nome):\n    pass\n", "Use split(), percorra as partes e acumule parte[0].upper().", "def iniciais(nome):\n    resultado = \"\"\n    for parte in nome.split():\n        resultado += parte[0].upper()\n    return resultado", "split() sem argumento ignora sequências extras de espaços.", ["strings", "lacos", "funcoes"]),
    fn("str-contar", "strings", "Contar uma substring", "conta_python", "Escreva conta_python(texto), que retorna quantas vezes 'python' aparece, ignorando maiúsculas.", "Use lower() e count().", [{ args: ["Python e PYTHON"], expected: 2 }, { args: ["java"], expected: 0 }, { args: ["pythonpython"], expected: 2 }], "def conta_python(texto):\n    pass\n", "Converta antes de contar.", "def conta_python(texto):\n    return texto.lower().count(\"python\")", "count() conta ocorrências não sobrepostas.", ["strings", "funcoes"]),
    program("str-fstring", "strings", "Apresentação com f-string", "Leia um nome e uma idade inteira. Mostre: NOME tem IDADE anos.", "Substitua NOME e IDADE pelos valores, sem textos extras.", [{ inputs: ["Ana", "20"], expected: "Ana tem 20 anos." }, { inputs: ["Leo", "7"], expected: "Leo tem 7 anos." }], "nome = input()\nidade = int(input())\n", "Use f\"{nome} tem {idade} anos.\".", "nome = input()\nidade = int(input())\nprint(f\"{nome} tem {idade} anos.\")", "F-strings avaliam expressões entre chaves.", ["strings", "entrada"]),

    // 05 · Entrada e saída (6 novos + dobro)
    trace("io-print", "entrada", "Separador do print", "Preveja exatamente a saída.", "a = 3\nb = 5\nprint(a, b)", "3 5", "print() usa um espaço entre argumentos por padrão.", "Vários argumentos evitam conversão manual para string.", ["entrada", "rastreamento"]),
    choice("io-input-str", "entrada", "O tipo de input()", "Depois de idade = input(), qual é o tipo de idade antes de qualquer conversão?", ["int", "float", "str", "Depende do que foi digitado"], 2, "input() sempre devolve texto.", "Mesmo que a pessoa digite 20, o resultado inicial é '20'.", ["entrada", "tipos"]),
    program("io-saudacao", "entrada", "Saudar pelo nome", "Leia um nome e mostre: Olá, NOME!", "Não acrescente perguntas ou outros textos.", [{ inputs: ["Bia"], expected: "Olá, Bia!" }, { inputs: ["Linus"], expected: "Olá, Linus!" }], "nome = input()\n", "Use uma f-string ou passe partes ao print com sep adequado.", "nome = input()\nprint(f\"Olá, {nome}!\")", "O texto do input não deve conter prompt quando a saída é avaliada.", ["entrada", "strings"]),
    program("io-idade-futura", "entrada", "Idade no próximo ano", "Leia uma idade inteira e mostre a idade no próximo ano.", "Imprima somente o número.", [{ inputs: ["20"], expected: "21" }, { inputs: ["0"], expected: "1" }, { inputs: ["99"], expected: "100" }], "idade = int(input())\n", "Some 1 depois da conversão.", "idade = int(input())\nprint(idade + 1)", "Sem int(), somar texto e número produz TypeError.", ["entrada", "numeros"]),
    program("io-area", "entrada", "Área de um retângulo", "Leia largura e altura como números decimais e mostre a área.", "Use dois input(), float() e imprima somente o resultado.", [{ inputs: ["3", "4"], expected: "12.0" }, { inputs: ["2.5", "4"], expected: "10.0" }, { inputs: ["0", "8"], expected: "0.0" }], "largura = float(input())\n", "Área é largura * altura.", "largura = float(input())\naltura = float(input())\nprint(largura * altura)", "Zero é um caso-limite útil.", ["entrada", "numeros"], { numericOutput: true }),
    order("io-fluxo", "entrada", "Do teclado à tela", "Organize um programa conceitual que lê um preço, aplica 10% de desconto e mostra o resultado.", ["Ler o preço como número", "Calcular preço * 0.9", "Guardar o resultado", "Mostrar o resultado"], "Não é possível calcular antes de obter e converter a entrada.", "Separar o fluxo evita misturar leitura, cálculo e apresentação.", ["entrada", "logica"]),

    // 06 · Condições (6 novos + 3 existentes)
    trace("cond-bool", "condicoes", "Combinar comparações", "Preveja as duas linhas.", "x = 8\nprint(x > 5 and x < 10)\nprint(x == 8 or x < 0)", "True\nTrue", "Avalie cada comparação antes de aplicar and/or.", "and exige ambas; or exige ao menos uma.", ["condicoes", "rastreamento"]),
    program("cond-faixa", "condicoes", "Dentro do intervalo", "Leia um inteiro e mostre 'dentro' se estiver entre 10 e 20 inclusive; caso contrário, mostre 'fora'.", "Use and ou uma comparação encadeada.", [{ inputs: ["10"], expected: "dentro" }, { inputs: ["20"], expected: "dentro" }, { inputs: ["15"], expected: "dentro" }, { inputs: ["9"], expected: "fora" }, { inputs: ["21"], expected: "fora" }], "numero = int(input())\n", "10 <= numero <= 20 expressa os dois limites.", "numero = int(input())\nif 10 <= numero <= 20:\n    print(\"dentro\")\nelse:\n    print(\"fora\")", "Testar exatamente 10 e 20 revela erros de >= e <=.", ["condicoes", "entrada"]),
    program("cond-bissexto-simples", "condicoes", "Divisível por dois números", "Leia um inteiro e mostre 'sim' se for divisível por 3 e por 5; senão, mostre 'nao'.", "Use %, comparação e and.", [{ inputs: ["15"], expected: "sim" }, { inputs: ["30"], expected: "sim" }, { inputs: ["9"], expected: "nao" }, { inputs: ["10"], expected: "nao" }, { inputs: ["0"], expected: "sim" }], "numero = int(input())\n", "Resto zero indica divisibilidade.", "numero = int(input())\nif numero % 3 == 0 and numero % 5 == 0:\n    print(\"sim\")\nelse:\n    print(\"nao\")", "Zero é divisível por qualquer inteiro não nulo.", ["condicoes", "numeros"]),
    program("cond-vogal", "condicoes", "Uma letra é vogal?", "Leia uma letra e mostre 'vogal' ou 'consoante'. Considere maiúsculas.", "As entradas são letras sem acento.", [{ inputs: ["a"], expected: "vogal" }, { inputs: ["E"], expected: "vogal" }, { inputs: ["x"], expected: "consoante" }], "letra = input().lower()\n", "Teste pertencimento em 'aeiou'.", "letra = input().lower()\nif letra in \"aeiou\":\n    print(\"vogal\")\nelse:\n    print(\"consoante\")", "in também funciona em strings.", ["condicoes", "strings"]),
    program("cond-triangulo", "condicoes", "Pode formar triângulo?", "Leia três números positivos. Mostre 'sim' se cada lado for menor que a soma dos outros dois; senão, 'nao'.", "Use and para combinar as três desigualdades.", [{ inputs: ["3", "4", "5"], expected: "sim" }, { inputs: ["1", "2", "3"], expected: "nao" }, { inputs: ["5", "5", "9"], expected: "sim" }], "a = float(input())\nb = float(input())\nc = float(input())\n", "Teste a < b+c, b < a+c e c < a+b.", "a = float(input())\nb = float(input())\nc = float(input())\nif a < b + c and b < a + c and c < a + b:\n    print(\"sim\")\nelse:\n    print(\"nao\")", "A igualdade representa um triângulo degenerado e não passa.", ["condicoes", "numeros"]),
    trace("cond-aninhada", "condicoes", "Qual bloco executa?", "Acompanhe as duas decisões.", "x = 7\nif x > 0:\n    if x % 2 == 0:\n        print(\"A\")\n    else:\n        print(\"B\")\nelse:\n    print(\"C\")", "B", "7 é positivo, mas não é par.", "A indentação mostra qual else pertence a qual if.", ["condicoes", "rastreamento"]),

    // 07 · Laços (7 novos + 3 existentes)
    trace("loop-range-zero", "lacos", "range começa em zero", "Preveja as três linhas.", "for n in range(3):\n    print(n)", "0\n1\n2", "range(3) gera 0, 1 e 2.", "Com um argumento, o início padrão é zero.", ["lacos", "rastreamento"]),
    trace("loop-range-step", "lacos", "Passos de dois", "Preveja a sequência.", "for n in range(2, 9, 2):\n    print(n)", "2\n4\n6\n8", "O terceiro argumento é o passo.", "O limite 9 fica de fora, mas 8 entra.", ["lacos", "rastreamento"]),
    program("loop-soma-pares", "lacos", "Somar apenas os pares", "Leia n >= 0 e some os números pares de 0 até n, incluindo n.", "Use for e range().", [{ inputs: ["6"], expected: "12" }, { inputs: ["5"], expected: "6" }, { inputs: ["0"], expected: "0" }, { inputs: ["10"], expected: "30" }], "n = int(input())\ntotal = 0\n", "Você pode usar range(0, n + 1, 2).", "n = int(input())\ntotal = 0\nfor numero in range(0, n + 1, 2):\n    total += numero\nprint(total)", "Somar por passo evita um if dentro do laço.", ["lacos", "acumuladores"], { requireLoop: "for" }),
    program("loop-while-regressiva", "lacos", "Contagem regressiva", "Leia n >= 1 e mostre de n até 1, um por linha, usando while.", "Diminua o contador para garantir a parada.", [{ inputs: ["3"], expected: "3\n2\n1" }, { inputs: ["1"], expected: "1" }, { inputs: ["5"], expected: "5\n4\n3\n2\n1" }], "n = int(input())\n", "Enquanto n >= 1, mostre e diminua n.", "n = int(input())\nwhile n >= 1:\n    print(n)\n    n -= 1", "Atualizar na direção errada criaria um laço infinito.", ["lacos", "acumuladores"], { requireLoop: "while" }),
    fn("loop-primeiro-negativo", "lacos", "Parar ao encontrar", "primeiro_negativo", "Escreva primeiro_negativo(numeros), que retorna o primeiro negativo ou None se não houver.", "Use for; pode retornar assim que encontrar.", [{ args: [[4, 2, -3, -8]], expected: -3 }, { args: [[-1, 5]], expected: -1 }, { args: [[1, 2, 3]], expected: null }, { args: [[]], expected: null }], "def primeiro_negativo(numeros):\n    pass\n", "Percorra e teste numero < 0. Depois do laço, retorne None.", "def primeiro_negativo(numeros):\n    for numero in numeros:\n        if numero < 0:\n            return numero\n    return None", "return pode encerrar a busca antecipadamente.", ["lacos", "listas", "retorno"], { requireLoop: "for" }),
    program("loop-conta-espacos", "lacos", "Contar espaços", "Leia um texto e mostre quantos caracteres de espaço ele contém.", "Use for e um contador.", [{ inputs: ["um dia"], expected: "1" }, { inputs: ["a b c"], expected: "2" }, { inputs: ["sem_espaco"], expected: "0" }, { inputs: [""], expected: "0" }], "texto = input()\nquantidade = 0\n", "Compare cada caractere com ' '.", "texto = input()\nquantidade = 0\nfor caractere in texto:\n    if caractere == \" \":\n        quantidade += 1\nprint(quantidade)", "Espaço é um caractere como qualquer outro.", ["lacos", "strings", "acumuladores"], { requireLoop: "for" }),
    trace("loop-aninhado", "lacos", "Um laço dentro do outro", "Quantas linhas e quais valores aparecem?", "for i in range(2):\n    for j in range(2):\n        print(i, j)", "0 0\n0 1\n1 0\n1 1", "Para cada i, o laço de j executa inteiro.", "Dois laços de tamanho 2 produzem 2 × 2 iterações.", ["lacos", "rastreamento"]),

    // 08 · Listas (2 novos + 8 existentes)
    trace("lista-indices", "listas", "Alterar um elemento", "Preveja a lista final.", "valores = [10, 20, 30]\nvalores[1] = 99\nprint(valores)", "[10, 99, 30]", "O índice 1 é o segundo elemento.", "Listas são mutáveis.", ["listas", "rastreamento"]),
    fn("lista-recorte", "listas", "Recortar sem alterar", "meio", "Escreva meio(valores), que retorna uma nova lista sem o primeiro e o último elemento.", "Use slicing. Para listas com menos de 3 itens, retorne lista vazia.", [{ args: [[1, 2, 3, 4]], expected: [2, 3] }, { args: [[1, 2]], expected: [] }, { args: [[]], expected: [] }, { args: [[5, 6, 7]], expected: [6] }], "def meio(valores):\n    pass\n", "valores[1:-1] seleciona depois do primeiro e antes do último.", "def meio(valores):\n    return valores[1:-1]", "Slicing fora dos limites é seguro e devolve uma lista menor ou vazia.", ["listas", "funcoes"]),

    // 09 · Funções (6 novos + 3 existentes)
    choice("func-parametro", "funcoes", "Parâmetro e argumento", "Em dobro(5), considerando def dobro(numero), qual item é o argumento?", ["dobro", "numero", "5", "def"], 2, "Argumento é o valor usado na chamada.", "numero é o parâmetro formal; 5 é o argumento real.", ["funcoes"]),
    trace("func-chamada", "funcoes", "Definir não é chamar", "Preveja a única linha mostrada.", "def soma(a, b):\n    return a + b\n\nresultado = soma(2, 3)\nprint(resultado)", "5", "A definição prepara a função; soma(2, 3) executa o corpo.", "return entrega 5 para a variável resultado.", ["funcoes", "retorno", "rastreamento"]),
    fn("func-padrao", "funcoes", "Parâmetro padrão", "saudacao", "Escreva saudacao(nome='mundo'), que retorna 'Olá, NOME!'.", "A função deve funcionar com e sem argumento.", [{ args: [], expected: "Olá, mundo!" }, { args: ["Ada"], expected: "Olá, Ada!" }], "def saudacao(nome=\"mundo\"):\n    pass\n", "Use o parâmetro dentro de uma f-string.", "def saudacao(nome=\"mundo\"):\n    return f\"Olá, {nome}!\"", "O valor padrão só é usado quando o argumento é omitido.", ["funcoes", "strings", "retorno"]),
    trace("func-escopo", "funcoes", "Variável local", "Preveja as duas linhas.", "x = 10\ndef altera():\n    x = 3\n    print(x)\naltera()\nprint(x)", "3\n10", "O x criado dentro da função é local.", "A atribuição local não modifica automaticamente o x global.", ["funcoes", "variaveis", "rastreamento"]),
    fn("func-primeiro-par", "funcoes", "Retorno antecipado", "primeiro_par", "Escreva primeiro_par(numeros), que retorna o primeiro par ou None.", "Não continue procurando depois de encontrar.", [{ args: [[1, 3, 4, 6]], expected: 4 }, { args: [[2, 8]], expected: 2 }, { args: [[1, 3]], expected: null }, { args: [[]], expected: null }], "def primeiro_par(numeros):\n    pass\n", "return dentro do if encerra a função; None vem depois do laço.", "def primeiro_par(numeros):\n    for numero in numeros:\n        if numero % 2 == 0:\n            return numero\n    return None", "A posição do return muda completamente o algoritmo.", ["funcoes", "listas", "retorno"], { requireLoop: "for" }),
    fn("func-composicao", "funcoes", "Uma função usa outra", "quadruplica", "Defina dobro(numero) e quadruplica(numero). quadruplica deve usar dobro duas vezes e retornar quatro vezes o valor.", "Escreva as duas funções.", [{ args: [3], expected: 12 }, { args: [0], expected: 0 }, { args: [-2], expected: -8 }], "def dobro(numero):\n    return numero * 2\n\ndef quadruplica(numero):\n    pass\n", "dobro(dobro(numero)) reaproveita a abstração.", "def dobro(numero):\n    return numero * 2\n\ndef quadruplica(numero):\n    return dobro(dobro(numero))", "Funções pequenas podem ser compostas em operações maiores.", ["funcoes", "retorno"]),

    // 10 · Depuração e integração (7 novos + 2 existentes)
    choice("debug-syntax", "depuracao", "Reconhecer SyntaxError", "Qual linha produz SyntaxError?", ["print(10)", "x = 3", "if x > 0", "nome = 'Ana'"], 2, "Um cabeçalho de if precisa terminar em dois-pontos.", "SyntaxError indica que o código não respeita a gramática.", ["depuracao", "sintaxe"]),
    choice("debug-name", "depuracao", "Reconhecer NameError", "Qual trecho tenta usar um nome que não existe?", ["x = 2\nprint(x)", "print(total)", "print(3 + 4)", "nome = input()"], 1, "Procure um nome usado antes de qualquer atribuição.", "NameError costuma envolver digitação ou ordem das instruções.", ["depuracao", "variaveis"]),
    choice("debug-type", "depuracao", "Reconhecer TypeError", "Qual expressão produz TypeError?", ["3 + 4", "'3' + '4'", "int('3') + 4", "'3' + 4"], 3, "Texto e inteiro não são somados diretamente.", "Converta ou escolha uma operação coerente com os tipos.", ["depuracao", "tipos"]),
    choice("debug-index", "depuracao", "Reconhecer IndexError", "Para lista = [10, 20, 30], qual acesso está fora dos limites?", ["lista[0]", "lista[2]", "lista[-1]", "lista[3]"], 3, "Três elementos ocupam índices 0, 1 e 2.", "len(lista) é o primeiro índice inválido no lado positivo.", ["depuracao", "listas"]),
    choice("debug-infinito", "depuracao", "Por que nunca termina?", "No código x = 1; while x <= 5: print(x), o que está faltando?", ["Converter x para texto", "Atualizar x dentro do laço", "Um segundo print", "Trocar while por if"], 1, "A condição precisa caminhar em direção a False.", "Laços while exigem atenção explícita à atualização do estado.", ["depuracao", "lacos"]),
    choice("debug-casos", "depuracao", "Um conjunto de testes melhor", "Para uma função que retorna o maior número de uma lista não vazia, qual conjunto encontra mais defeitos?", ["[1, 2, 3] apenas", "[5] apenas", "[1, 2, 3], [-5, -2] e [7]", "[100, 200] apenas"], 2, "Inclua um caso comum, negativos e lista unitária.", "Casos diversos testam suposições escondidas, como iniciar o maior em zero.", ["depuracao", "logica"]),
    fn("debug-divisao", "depuracao", "Corrigir divisão segura", "divide", "Corrija divide(a, b): ela deve retornar a / b, mas retornar None quando b for zero.", "Não deixe ZeroDivisionError escapar.", [{ args: [10, 2], expected: 5 }, { args: [5, 0], expected: null }, { args: [-9, 3], expected: -3 }], "def divide(a, b):\n    return a / b\n", "Teste b == 0 antes da divisão.", "def divide(a, b):\n    if b == 0:\n        return None\n    return a / b", "Tratar explicitamente o caso inválido torna o contrato previsível.", ["depuracao", "condicoes", "funcoes", "retorno"])
  ];

  const existingPlacement = {
    ola: ["sintaxe", ["sintaxe"]], dobro: ["entrada", ["entrada", "tipos"]], media: ["numeros", ["numeros", "entrada"]], divisao: ["numeros", ["numeros", "entrada"]],
    aprovado: ["condicoes", ["condicoes", "entrada"]], sinal: ["condicoes", ["condicoes"]], maior_dois: ["condicoes", ["condicoes", "entrada"]],
    contagem: ["lacos", ["lacos", "sintaxe"]], tabuada: ["lacos", ["lacos", "entrada"]], soma_ate: ["lacos", ["lacos", "acumuladores"]],
    vogais: ["strings", ["strings", "lacos", "acumuladores"]], dobro_funcao: ["funcoes", ["funcoes", "retorno"]], classifica: ["funcoes", ["funcoes", "retorno", "condicoes"]],
    soma: ["listas", ["listas", "lacos", "acumuladores"]], pares: ["listas", ["listas", "lacos", "acumuladores"]], maior: ["listas", ["listas", "lacos", "condicoes"]], menor: ["listas", ["listas", "lacos", "condicoes"]],
    media_lista: ["listas", ["listas", "acumuladores", "retorno"]], filtra_pares: ["listas", ["listas", "lacos"]], busca: ["listas", ["listas", "condicoes", "retorno"]],
    mesa_range: ["depuracao", ["rastreamento", "lacos"]], mesa_acumulador: ["depuracao", ["rastreamento", "acumuladores"]], mesa_return: ["funcoes", ["rastreamento", "retorno", "funcoes"]], mesa_lista: ["listas", ["rastreamento", "listas"]]
  };

  window.EXERCISES.forEach(exercise => {
    const placement = existingPlacement[exercise.id];
    if (!placement) return;
    exercise.unit = placement[0]; exercise.group = group(placement[0]); exercise.skills = placement[1];
  });
  window.EXERCISES.push(...additions);
  window.EXERCISES.sort((a, b) => unitById[a.unit].order - unitById[b.unit].order || a.id.localeCompare(b.id, "pt-BR"));
  window.CURRICULUM = { units, unitById };
})();
