/* Atividades originais alinhadas aos tópicos de prdm0/curso_python. */
(function () {
  "use strict";
  const { units, unitById } = window.CURRICULUM;
  Object.assign(unitById.listas, {
    title: "Listas, tuplas, dicionários e conjuntos", short: "Estruturas",
    description: "Escolher coleções, copiar dados e combinar estruturas.",
    concepts: ["listas e cópias", "tuplas e desempacotamento", "dicionários e items()", "conjuntos e operações", "compreensões de listas"]
  });
  unitById.lacos.concepts.push("enumerate() e zip()", "break e continue");
  unitById.funcoes.concepts.push("*args e **kwargs", "lambda, map e reduce");
  const additions = [];
  function base(id, unit, title, skills) {
    return { id: "curso-" + id, unit, title, skills, courseAligned: true,
      group: String(unitById[unit].order).padStart(2, "0") + " · " + unitById[unit].title };
  }
  function trace(id, unit, title, code, answer, note, skills = [unit, "rastreamento"]) {
    additions.push({ ...base(id, unit, title, skills), kind: "trace", prompt: "Acompanhe o código e escreva a saída, uma linha por vez.",
      rule: "Resolva sem executar. A ordem dos conjuntos não é usada como resposta.", code, answer, starter: "", hint: note, solution: answer, note });
  }
  function fn(id, unit, title, name, prompt, cases, solution, note, skills = [unit, "funcoes", "retorno"]) {
    additions.push({ ...base(id, unit, title, skills), kind: "function", fn: name, prompt,
      rule: "Retorne o resultado; não imprima. Confira também os casos-limite.", cases,
      starter: solution.split("\n")[0] + "\n    pass", hint: note, solution, note });
  }
  function choice(id, unit, title, prompt, options, correct, note, skills = [unit]) {
    additions.push({ ...base(id, unit, title, skills), kind: "choice", prompt,
      rule: "Escolha uma alternativa antes de verificar.", options: options.map((label, index) => ({ value: String(index), label })),
      answer: String(correct), starter: "", hint: note, solution: options[correct], note });
  }
  trace("identidade", "variaveis", "Igualdade e identidade", "a = [2, 4]\nb = a\nc = a.copy()\nprint(a == c)\nprint(a is c)\nprint(a is b)", "True\nFalse\nTrue", "== compara valores; is compara identidade. A cópia cria outra lista.");
  trace("isinstance", "variaveis", "Reconhecer tipos", "print(isinstance(2.5, float))\nprint(type((7,)).__name__)\nprint(type({}).__name__)", "True\ntuple\ndict", "Uma vírgula cria a tupla unitária. {} cria um dicionário vazio.");
  trace("math", "numeros", "Importar math", "import math\nprint(math.isqrt(50))\nprint(math.factorial(0))\nprint(round(math.sqrt(2), 2))", "7\n1\n1.41", "isqrt dá a raiz inteira. Atenção: 0! = 1, apesar do lapso no slide de fatorial.");
  trace("formatacao", "strings", "Casas decimais e alinhamento", "valor = 3.5\nprint(f'{valor:.2f}')\nprint(f'{7:03d}')\nprint('a', 'b', sep='-', end='!')", "3.50\n007\na-b!", ".2f fixa duas casas; 03d preenche com zeros; sep e end controlam a saída.");
  fn("palindromo", "strings", "Palíndromo normalizado", "palindromo", "Escreva palindromo(texto). Ignore espaços e diferenças de maiúsculas; retorne True se o texto normalizado for igual ao reverso. Considere apenas letras sem acentos e espaços.", [{ args: ["Ovo"], expected: true }, { args: ["Anotaram a data da maratona"], expected: true }, { args: ["python"], expected: false }, { args: [""], expected: true }], "def palindromo(texto):\n    limpo = texto.lower().replace(' ', '')\n    return limpo == limpo[::-1]", "[::-1] inverte a sequência; normalize antes de comparar.");
  fn("tarifa", "condicoes", "Tarifa por faixa", "tarifa", "Escreva tarifa(consumo). O valor de cada unidade é 0.40 se consumo <= 500 e 0.65 acima disso. Aplique a tarifa da faixa ao consumo inteiro e retorne o total. Consumo é não negativo.", [{ args: [0], expected: 0 }, { args: [500], expected: 200 }, { args: [501], expected: 325.65 }], "def tarifa(consumo):\n    if consumo <= 500:\n        return consumo * 0.40\n    return consumo * 0.65", "Teste a fronteira: 500 pertence à primeira faixa; 501 pertence à segunda.");
  fn("emprestimo", "condicoes", "Limite de uma prestação", "aprova", "Escreva aprova(valor, salario, anos). Retorne True se valor / (anos * 12) for no máximo 30% do salário. Retorne False se anos <= 0. Valor e salário são não negativos.", [{ args: [36000, 1000, 10], expected: true }, { args: [36001, 1000, 10], expected: false }, { args: [200, 100, 0], expected: false }], "def aprova(valor, salario, anos):\n    if anos <= 0:\n        return False\n    return valor / (anos * 12) <= salario * 0.30", "Converta anos para meses e use <= para aceitar o limite exato.");
  trace("enumerate", "lacos", "Enumerar observações", "nomes = ['Ana', 'Bia']\nfor indice, nome in enumerate(nomes, start=1):\n    print(indice, nome)", "1 Ana\n2 Bia", "enumerate fornece posição e valor; start muda a numeração.");
  trace("zip", "lacos", "Combinar sequências", "for nome, nota in zip(['Ana', 'Bia', 'Caio'], [8, 6]):\n    print(nome, nota)", "Ana 8\nBia 6", "zip para ao terminar a sequência mais curta.");
  trace("break-continue", "lacos", "Pular e encerrar", "for n in range(1, 7):\n    if n == 2:\n        continue\n    if n == 5:\n        break\n    print(n)", "1\n3\n4", "continue pula só a iteração atual; break encerra o laço mais próximo.");
  fn("fatorial", "lacos", "Fatorial com acumulador", "fatorial", "Escreva fatorial(n) para um inteiro n >= 0. Use um laço e retorne o produto de 1 até n; para zero, retorne 1.", [{ args: [0], expected: 1 }, { args: [1], expected: 1 }, { args: [5], expected: 120 }, { args: [7], expected: 5040 }], "def fatorial(n):\n    resultado = 1\n    for i in range(1, n + 1):\n        resultado *= i\n    return resultado", "O elemento neutro da multiplicação é 1. O laço vazio preserva 0! = 1.", ["lacos", "acumuladores", "retorno"]);
  additions[additions.length - 1].requireLoop = "for";
  fn("primos", "lacos", "Encontrar números primos", "primos", "Escreva primos(limite), que retorna em ordem os primos entre 2 e limite inclusive. Se limite < 2, retorne []. Use laços para testar divisores.", [{ args: [1], expected: [] }, { args: [2], expected: [2] }, { args: [12], expected: [2, 3, 5, 7, 11] }, { args: [25], expected: [2, 3, 5, 7, 11, 13, 17, 19, 23] }], "def primos(limite):\n    resultado = []\n    for numero in range(2, limite + 1):\n        primo = True\n        for divisor in range(2, numero):\n            if numero % divisor == 0:\n                primo = False\n                break\n        if primo:\n            resultado.append(numero)\n    return resultado", "1 não é primo. Ao encontrar um divisor, interrompa a busca.", ["lacos", "listas", "condicoes"]);
  additions[additions.length - 1].requireLoop = "for";
  trace("tupla", "listas", "Tuplas e desempacotamento", "ponto = (3, 8)\nx, y = ponto\nprint(x + y)\nprint(len((5,)))", "11\n1", "Tuplas são sequências imutáveis; a vírgula distingue (5,) de (5).");
  choice("tupla-mutacao", "listas", "O que uma tupla permite?", "Para ponto = (2, 9), qual operação é válida?", ["ponto[0] = 5", "ponto.append(5)", "x, y = ponto", "ponto.remove(2)"], 2, "É possível ler e desempacotar uma tupla, mas não reatribuir seus elementos.");
  trace("desempacotamento", "listas", "Capturar o restante", "primeiro, *meio, ultimo = [2, 4, 6, 8]\nprint(primeiro)\nprint(meio)\nprint(ultimo)", "2\n[4, 6]\n8", "O alvo com * recebe uma lista com os elementos restantes.");
  trace("dict-get", "listas", "Chaves e valores", "notas = {'Ana': 8, 'Bia': 6}\nprint('Ana' in notas)\nprint(8 in notas)\nprint(notas.get('Caio', 0))", "True\nFalse\n0", "in testa chaves do dicionário. get permite um valor padrão para chave ausente.");
  trace("dict-items", "listas", "Percorrer um dicionário", "precos = {'cafe': 4, 'pao': 2}\nfor produto, preco in precos.items():\n    print(produto, preco)", "cafe 4\npao 2", "items() fornece pares chave/valor. Dicionários preservam a ordem de inserção.");
  fn("frequencias", "listas", "Tabela de frequências", "frequencias", "Escreva frequencias(valores), retornando um dicionário com a quantidade de ocorrências de cada inteiro. Para uma lista vazia, retorne {}.", [{ args: [[2, 1, 2, 3, 1, 2]], expected: { 2: 3, 1: 2, 3: 1 } }, { args: [[]], expected: {} }, { args: [[-1, -1, 0]], expected: { "-1": 2, 0: 1 } }], "def frequencias(valores):\n    contagens = {}\n    for valor in valores:\n        chave = str(valor)\n        contagens[chave] = contagens.get(chave, 0) + 1\n    return contagens", "Use get(chave, 0) para inicializar a contagem. Neste exercício, as chaves retornadas são strings.", ["listas", "acumuladores", "lacos"]);
  additions[additions.length - 1].prompt = "Escreva frequencias(valores), retornando um dicionário cujas chaves são os inteiros convertidos para strings e cujos valores são as contagens. Para lista vazia, retorne {}. Exemplo: [2, 2] retorna {'2': 2}.";
  fn("medias-filiais", "listas", "Médias em estruturas aninhadas", "medias", "Escreva medias(vendas). A entrada tem o formato {'filial': {'produto': [valores]}}. Retorne a mesma estrutura com a média de cada lista; use 0 para uma lista vazia. Preserve as chaves.", [{ args: [{ norte: { cafe: [2, 4], pao: [10, 20] }, sul: { cafe: [6] } }], expected: { norte: { cafe: 3, pao: 15 }, sul: { cafe: 6 } } }, { args: [{ norte: { cafe: [] } }], expected: { norte: { cafe: 0 } } }, { args: [{}], expected: {} }], "def medias(vendas):\n    resultado = {}\n    for filial, produtos in vendas.items():\n        resultado[filial] = {}\n        for produto, valores in produtos.items():\n            resultado[filial][produto] = sum(valores) / len(valores) if valores else 0\n    return resultado", "Use dois laços com items(); crie um dicionário para cada filial.", ["listas", "lacos", "acumuladores"]);
  trace("conjuntos", "listas", "União, interseção e diferença", "a = {1, 2, 3}\nb = {3, 4}\nprint(sorted(a | b))\nprint(sorted(a & b))\nprint(sorted(a - b))\nprint(sorted(a ^ b))", "[1, 2, 3, 4]\n[3]\n[1, 2]\n[1, 2, 4]", "| une, & intersecta, - subtrai e ^ dá a diferença simétrica. sorted estabiliza a saída.");
  trace("set-vazio", "listas", "Conjunto vazio e repetidos", "valores = [3, 3, 1, 1, 2]\nprint(len(set(valores)))\nprint(type(set()).__name__)\nprint({1, 2} <= {1, 2, 3})", "3\nset\nTrue", "set remove duplicatas; set() cria conjunto vazio; <= verifica subconjunto.");
  fn("unicos", "listas", "Valores distintos em ordem", "unicos", "Escreva unicos(valores), retornando uma lista ordenada dos inteiros distintos presentes na entrada.", [{ args: [[3, 1, 3, 2]], expected: [1, 2, 3] }, { args: [[]], expected: [] }, { args: [[-2, 0, -2]], expected: [-2, 0] }], "def unicos(valores):\n    return sorted(set(valores))", "Converta para set e ordene o resultado.");
  trace("copia-sort", "listas", "Cópia, sort e sorted", "a = [3, 1, 2]\nb = sorted(a)\nc = a.copy()\nretorno = c.sort()\nprint(a)\nprint(b)\nprint(retorno)", "[3, 1, 2]\n[1, 2, 3]\nNone", "sorted cria uma lista; sort modifica a própria lista e retorna None.");
  trace("compreensao", "listas", "Filtrar com compreensão", "valores = [1, 2, 3, 4, 5]\nprint([n ** 2 for n in valores if n % 2 != 0])", "[1, 9, 25]", "Leia: para cada n, filtre os ímpares e então calcule n ** 2.");
  fn("quadrados-pares", "listas", "Escrever uma compreensão", "quadrados_pares", "Escreva quadrados_pares(valores), retornando os quadrados dos valores pares na ordem original. Resolva com compreensão de lista.", [{ args: [[1, 2, 3, 4]], expected: [4, 16] }, { args: [[-2, 0, 5]], expected: [4, 0] }, { args: [[]], expected: [] }], "def quadrados_pares(valores):\n    return [n ** 2 for n in valores if n % 2 == 0]", "A condição fica depois do for na compreensão.");
  additions[additions.length - 1].requireComprehension = true;
  trace("compreensao-if", "listas", "Transformar ou filtrar?", "print(['par' if n % 2 == 0 else 'impar' for n in range(4)])", "['par', 'impar', 'par', 'impar']", "if/else antes do for transforma cada item. if depois do for filtra itens.");
  trace("compreensao-aninhada", "listas", "Compreensão com dois laços", "print([(i, j) for i in range(2) for j in range(2)])", "[(0, 0), (0, 1), (1, 0), (1, 1)]", "A ordem dos for é a mesma da versão com laços aninhados.");
  trace("args", "funcoes", "Argumentos posicionais variáveis", "def soma(*valores):\n    return sum(valores)\nprint(soma())\nprint(soma(2, 3, 4))", "0\n9", "*args reúne argumentos posicionais em uma tupla.");
  trace("kwargs", "funcoes", "Argumentos nomeados variáveis", "def consulta(**dados):\n    return dados.get('nota', 0)\nprint(consulta(nome='Ana', nota=8))\nprint(consulta(nome='Bia'))", "8\n0", "**kwargs reúne argumentos nomeados em um dicionário.");
  trace("expandir-args", "funcoes", "Expandir argumentos na chamada", "def soma(a, b):\n    return a + b\nprint(soma(*[2, 5]))\nprint(soma(**{'a': 3, 'b': 4}))", "7\n7", "Na chamada, * expande uma sequência; ** expande um dicionário de argumentos nomeados.");
  trace("lambda-map", "funcoes", "lambda e map", "dobro = lambda n: n * 2\nprint(dobro(3))\nprint(list(map(dobro, [1, 2, 3])))", "6\n[2, 4, 6]", "lambda cria uma função de uma expressão. map devolve um iterador; list materializa os resultados.");
  trace("reduce", "funcoes", "Acumular com reduce", "from functools import reduce\nprint(reduce(lambda a, b: a + b, [2, 3, 4], 0))\nprint(reduce(lambda a, b: a * b, [], 1))", "9\n1", "reduce combina o acumulador e o próximo valor; o inicial resolve também a sequência vazia.");
  choice("padrao-mutavel", "funcoes", "Armadilha do padrão mutável", "Qual assinatura evita compartilhar a mesma lista entre chamadas, criando a lista dentro do corpo quando necessário?", ["def guarda(valor, lista=[]):", "def guarda(valor, lista=None):", "def guarda(valor, lista=list()):", "def guarda(valor, lista=[0]):"], 1, "Padrões são avaliados na definição. Use None e, dentro da função, if lista is None: lista = [].");
  fn("media-args", "funcoes", "Média de argumentos variáveis", "media_args", "Escreva media_args(*valores), retornando a média dos argumentos numéricos ou None quando não houver argumentos.", [{ args: [], expected: null }, { args: [2, 4, 6], expected: 4 }, { args: [-2, 2], expected: 0 }, { args: [3.5], expected: 3.5 }], "def media_args(*valores):\n    if not valores:\n        return None\n    return sum(valores) / len(valores)", "Os argumentos chegam como tupla; teste a tupla vazia antes de dividir.");
  fn("serie-exp", "numeros", "Aproximar uma série numérica", "exp_serie", "Escreva exp_serie(x, termos), somando x**n / n! para n de 0 até termos-1. termos >= 1. Retorne a soma finita, não math.exp(x).", [{ args: [0, 5], expected: 1 }, { args: [1, 4], expected: 2.6666666666666665 }, { args: [2, 3], expected: 5 }, { args: [-1, 3], expected: 0.5 }], "def exp_serie(x, termos):\n    import math\n    total = 0\n    for n in range(termos):\n        total += x ** n / math.factorial(n)\n    return total", "O termo n=0 é 1 porque 0! = 1. Some apenas o número de termos solicitado.", ["numeros", "lacos", "acumuladores"]);
  choice("turtle", "lacos", "Raciocinar sobre turtle", "Uma caneta executa quatro vezes forward(50) e left(90). Partindo da mesma posição e orientação, que figura ela fecha?", ["Triângulo", "Quadrado de lado 50", "Círculo de raio 50", "Linha reta de tamanho 200"], 1, "Quatro lados iguais com giros de 90 graus fecham um quadrado. A janela gráfica de turtle exige Python local.");
  window.EXERCISES.push(...additions);
  window.EXERCISES.forEach(exercise => { exercise.group = String(unitById[exercise.unit].order).padStart(2, "0") + " · " + unitById[exercise.unit].title; });
  window.EXERCISES.sort((a, b) => unitById[a.unit].order - unitById[b.unit].order || a.id.localeCompare(b.id, "pt-BR"));
  window.COURSE_REVIEW = {
    source: "https://github.com/prdm0/curso_python", added: additions.length,
    examPools: [["curso-tarifa", "curso-emprestimo"], ["curso-palindromo"], ["curso-fatorial", "curso-primos"], ["curso-frequencias", "curso-medias-filiais", "curso-unicos"], ["curso-quadrados-pares"], ["curso-media-args", "curso-serie-exp"]],
    reviewIds: ["curso-identidade", "curso-tupla", "curso-dict-get", "curso-conjuntos", "curso-enumerate", "curso-zip", "curso-break-continue", "curso-compreensao", "curso-lambda-map", "curso-args", "curso-fatorial", "curso-medias-filiais"]
  };
})();
